default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: getmyaddress_development
  
test:
  <<: *default
  database: getmyaddress_test

production:
  <<: *default
  database: getmyaddress_production
  username: getmyaddress
  password: <%= ENV['GETMYADDRESS_DATABASE_PASSWORD'] %>
